/**
 * Agent Desk v2 — Port Allocation & .env Generation
 */

import * as fs from 'fs';
import * as net from 'net';
import * as path from 'path';
import * as crypto from 'crypto';
import type { DeskPorts } from './types.js';
import { PORT_BASES, PORT_STRIDE } from './types.js';

/**
 * Extract numeric index from desk name.
 * "desk-1" -> 1, "desk-review" -> hash-based fallback (50-99 range).
 */
export function extractDeskIndex(name: string): number {
  const match = name.match(/(\d+)$/);
  if (match) return parseInt(match[1], 10);

  // Hash-based fallback for non-numeric names
  const hash = crypto.createHash('md5').update(name).digest();
  return 50 + (hash[0] % 50); // Range 50-99 to avoid collision with numeric desks
}

/**
 * Calculate ports for a desk index.
 */
export function calculatePorts(index: number): DeskPorts {
  const offset = index * PORT_STRIDE;
  return {
    api: PORT_BASES.api + offset,
    mcp: PORT_BASES.mcp + offset,
    web: PORT_BASES.web + offset,
    dev: PORT_BASES.dev + offset,
  };
}

/**
 * Check if a port is available (not in use).
 */
export function checkPortAvailable(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(false));
    server.once('listening', () => {
      server.close(() => resolve(true));
    });
    server.listen(port, '127.0.0.1');
  });
}

/**
 * Check multiple ports, return list of occupied ones.
 */
export async function checkPortConflicts(ports: number[]): Promise<number[]> {
  const results = await Promise.all(
    ports.map(async (port) => ({ port, available: await checkPortAvailable(port) }))
  );
  return results.filter((r) => !r.available).map((r) => r.port);
}

/**
 * Write .env file with port assignments.
 */
export function writeEnvFile(deskPath: string, ports: DeskPorts): void {
  const content = `# Auto-generated by SidStack Agent Desk
# Do not edit manually

SIDSTACK_API_PORT=${ports.api}
SIDSTACK_MCP_PORT=${ports.mcp}
SIDSTACK_WEB_PORT=${ports.web}
SIDSTACK_DEV_PORT=${ports.dev}
`;

  fs.writeFileSync(path.join(deskPath, '.env'), content, 'utf-8');
}
